sudo: required

language: python
python:
  - 2.7

env:
  global:
    - secure: "DrT0Ymq69sUk8pirlUYDp+Zsv+5SnjOoJ3Uz7dyGWEXoC5XMFVCa1teHAUOBAy0rzNQBJpAHtKTyTWjn/mEiKHZoLnxPQpAEXvDClhFUxROXSoAmtCmMEjpwoXIaTGd9su5pPr3kT/YEJLXbT9aEPAf6p/Prp5Hp0XtdVhpBdycGiNVde369CeSgMeK1aFIV5KeDioLl2iwb5ap3aL/n56ar109p/0SQrt7ILX5koWzZ5ZiinHIwLe8ePK9HZOe2+NIiVj09ketMuYZOieAHtMj79TYtU5M/io0zh6G9V6efooN7uk01Tk/p+o6rKq/DqbzSmTDJdtX1j388IL7SiQit5ONaVNBlKmzlO9iI8kb1vEhCA5Q0RLYuf64gtJ7FS1fqB0VEMKca2632uV79dOItHq6SplaLh+KR2tLWZ04IkvB3qecFE8pUo76TddmV9256b4dXq5g1S+iqvR5DGg/N10J/toGDJd7wlRAF98x+02oIWdSPHSxlF3105X9534DXLI3qH3s2vKrizA7uNca31iQnBA/lQOKhrBujc3zGt9e3Qf/ikkUuHbDB0cYTdy2f4d4xij1F3sTFEasdBZhv/G5/zbrbWicjPf275qv5PQzxuPKMUbN/XF6YNHoLt50STy7HVg4/2kNnW8ADoXmnxBS8eksOTL7OcLY9wbQ=" #DOCKER_EMAIL
    - secure: "m7F9A1aUUhdJZL2UUXy3FSmS/jfRJG+4yMzJOvIJcRbpYaORDlLsvnXovC32MUbyP20ezHAyzy+zFy/Jmsf7uJB2u8izvwDRENDom1VqNkH9YOgGQxHqvbWoxU3CgrFY/5QXu8JWPKf1MIn7kZzuOG3wb3sauSyQfduJv71TgB2IL4GT50mxrAboZo/r7cnahzH624ngzEN6Cux9oipYjv5IUVAEUNZ85Lw7qC5pa5m34ZgeV9YN7hcdYPTy50R3UcxcXXdz7GpUWGxlLOuGnZreqHtD0GjI/Pf7g40nNyP5UrLFGQxGVyvoUNEU/aZRoINDnkG0jNanRbDdT+sXRXn5SHMxn5yv3BhEL77Cd1PmVWZWerXwdAW6y5+YdKuk0dJQC0bfajvstLu3srOFVJBuUlIXuvlHUA6Wbkln3WigrCjbxIlCPYkZT5yNdrMlhLZcXDLu8V5SK2OTSlV75ThO8SqMmB5axK/XMMsKwCDLrFm1lF4JBOzpt/ZnJSgAzSZiQgXH4AAYWJpdVZ5YYBYAAdjUV/OYNKV9t6dz5VCR9aHPVg6qKa4KSQIMGNoW+J9qwmOEol3ZdlKT2VUBs1DYF/WKsXGM1YXhTGk4Hg/ffoVvoWgxR6hK8XONU7J/zZ9mWmq1ODy3GiWBCQ5yqXzvvh6Lx097RQpoPSNwNvA=" #DOCKER_USER
    - secure: "anzhRrsDDhvgC6ih7OWiQ3c/cpcgVohzWVVKHv4v5B6Kphfx7vZtipIc9unhsza86nAdizRE+4KjAZyC3THVSFi4+SfhMV/xSvfnNqS0wrmy72E3j+HaX6wIvhdN9+1WFIcObvdPQSiqmpVrz28XpZAN2+bGD3VUVYPMUlNptA06M7Pf1lSEeIxj1NpYwZIRZ1nEzbGK9CpK/C3qxJtUxuX1HWfUIevqpdy380C1KoPW9H32i8gze2VjRVd5tL2887nLguk59ypeiZIDYrVzt+UnTJ7NDBNip11jsn79gGTduI/qu5c8XZ8cLWmfyBAAdD3vc98Y4oiDiH2QuSs2iCM6+eodI1J3g5IX8auwn5m4z+qZQ6ZgtK9ioGsB2PEtcnuKAAhtU2N7lENB2vVl4oqTYa97KpskCVM9kFmzAvuu8NGy0skezpAEy8Y83TDDqGO0VCFI8zGvtXqjJbnegjU5hryKCAF39b6CURZgXYdMXmjjDoEessTbehm5V9blVPVB4OnoHIZ848YBra+1QN+IE2q8DSGvvovZADB7JpbwVv0UjBogyWU30WwGW7KrJ4cdHKAkkY4BLb5Suf54n47wwYJADRKRzmf5TblOhTfxI1pJU5lk6bI11SeOn04UWBxl9STUXOlbqa7jRcmyyHtjx+ipSPYYFWqILegGVGY=" #DOCKER_PASS

services:
  - docker

install:
  - docker build -t whois-docker . --no-cache

script:
  - docker run --rm -it whois-docker --version | grep "Version 5.3.0"

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag whois-docker cardonator/whois:latest
  - docker push cardonator/whois
