name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: rfc1036/whois
        id: whois  # The step ID to refer to later.
    
      - uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: cardonator
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push whois docker
        uses: docker/build-push-action@v3
        with:
          context: "."
          target: whois
          push: true
          tags: cardonator/whois:latest,cardonator/whois:${{ steps.whois.outputs.tag }},ghcr.io/cardonator/whois-docker:latest,ghcr.io/cardonator/whois-docker:${{ steps.whois.outputs.tag }}

      - name: Build and push mkpasswd docker
        uses: docker/build-push-action@v3
        with:
          context: "."
          target: mkpasswd
          push: true
          tags: cardonator/mkpasswd:latest,cardonator/mkpasswd:${{ steps.whois.outputs.tag }},ghcr.io/cardonator/whois-docker:mkpasswd-latest,ghcr.io/cardonator/whois-docker:mkpasswd-${{ steps.whois.outputs.tag }}
